### PR TITLE
added codes

### PR DESCRIPTION
**Pull request by KSkoropad**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Added codes to draw the scatter plots, box plots logistic resression
## Checklist
- [ ] I can confirm that my changes are working as intended
@anjali-deshpande-hub @adithya28 @zrasi

### CODE REVIEW

**Comment by anjali-deshpande-hub** [comment]
Thank you Kateryna! I am in the process of reviewing this code.

**Comment by anjali-deshpande-hub** [comment]
Hello Kateryna,

Following are my review comments. Please make the required changes and ask for a re-review.

**Run errors**

The code gave me errors when I ran the file because the import statements are missing. Add  this block at the top to remove errors:

from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

**Box and Scatter Plot**

1. Could you please provide your insights from the plots (both box plot and scatter plot)? You can include a metadata block after the output. For example: "The box plot illustrates the median, spread, potential outliers, and skewness/symmetry of the data. You could comment on some these aspects. The scatter plot indicates patterns, trends, relationships, presence of outliers, and data density or sparsity. You describe what you observe.

2. Please remove "# Kateryna",”# add code here”and “### To be done” comments. "# Add code for scatter plot" could be revised to convey specifics such as "Add scatter plot between <variable> and <variable>".

**Regression**

1. Would it be possible to include a table listing the p-values for each variable along with their respective coefficients (using the summarize method)? P-values can provide valuable insights into whether we should reject the null hypothesis. Please add your explanation of the observations following the summary table of coefficients and p-values.

2. I noticed that some predictors have been omitted from the model. Could you clarify the rationale behind this decision? You could include all variables, especially medication variables. That could enhance model comprehensiveness. If excluding them, you can list them in a comment and explain the reasons for their exclusion.

3. I love the model evaluation matrix (precision, recall table). Could you please summarize your understanding of this matrix in a summary after the table?

4. The table output using confusion_matrix method  is in text format. We could potentially modularize this code and create a function that provides a more visual output. Let's defer this task for now until we've completed coding all the models.
     
I  do see differences in the output blocks for the code blocks that were coded by me. We could be using different versions of packages/Python. I am not too worried about this. We can resolve it once we have all the code blocks checked in.

**Comment by KSkoropad** [comment]
Hi Anjali (@anjali-deshpande-hub)! Could you please review my last commit. Thank you!

**Comment by anjali-deshpande-hub** [comment]
Hi Kateryna!
The changes look good.
Could you please add newlines to the markup highlighted in the attached screenshot?
Screenshot 2024-06-25 234804

**Comment by anjali-deshpande-hub** [comment]
Also, I don't know if its possible to print the coefficients and p-values with features for Logistic regression  model build (See review comment 1. under Regression). I know its easy to list the table of coefficients and p-values if you use Logit method in statsmodels. I am not sure about listing the same with LogisticRegression method.

**Comment by anjali-deshpande-hub** [comment]
Printing of Coefficients can be skipped for now. Approved. Please merge.

**Pull request merged**
